// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TuFabricaDDD.Persistence.Contexts;

#nullable disable

namespace TuFabricaDDD.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TuFabricaDDD.Domain.Entities.Robot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Robots", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("Robot");
                });

            modelBuilder.Entity("TuFabricaDDD.Domain.Records.RobotStateChangeRecord", b =>
                {
                    b.Property<Guid>("RobotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurringTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("RobotId", "OccurringTime");

                    b.ToTable("RobotStateChangeRecords", (string)null);
                });

            modelBuilder.Entity("TuFabricaDDD.Domain.Entities.CleaningMobile", b =>
                {
                    b.HasBaseType("TuFabricaDDD.Domain.Entities.Robot");

                    b.Property<double>("BatteryLevelPercentage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision");

                    b.Property<double>("DetergentLevelPercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("DustbinCapacityPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("EquippedCleaningTools")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Locomotion")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<double>("WaterLevelPercentage")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("CleaningMobile");
                });

            modelBuilder.Entity("TuFabricaDDD.Domain.Entities.FixedRoboticArm", b =>
                {
                    b.HasBaseType("TuFabricaDDD.Domain.Entities.Robot");

                    b.Property<double>("ArmLengthInMeters")
                        .HasColumnType("double precision");

                    b.Property<string>("MountingPointId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("PayloadCapacityInKg")
                        .HasColumnType("double precision");

                    b.HasDiscriminator().HasValue("FixedRoboticArm");
                });

            modelBuilder.Entity("TuFabricaDDD.Domain.Entities.Humanoid", b =>
                {
                    b.HasBaseType("TuFabricaDDD.Domain.Entities.Robot");

                    b.Property<double>("BatteryLevelPercentage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision");

                    b.Property<string>("EquippedTools")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HasManipulators")
                        .HasColumnType("boolean");

                    b.Property<int>("Locomotion")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<string>("OperatingSystemVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue("Humanoid");
                });

            modelBuilder.Entity("TuFabricaDDD.Domain.Entities.LogisticsMobile", b =>
                {
                    b.HasBaseType("TuFabricaDDD.Domain.Entities.Robot");

                    b.Property<double>("BatteryLevelPercentage")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("double precision");

                    b.Property<string>("CurrentCargoDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<double>("CurrentPayloadWeightInKg")
                        .HasColumnType("double precision");

                    b.Property<int>("Locomotion")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer");

                    b.Property<double>("MaxPayloadCapacityInKg")
                        .HasColumnType("double precision");

                    b.Property<string>("NavigationSystemType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasDiscriminator().HasValue("LogisticsMobile");
                });

            modelBuilder.Entity("TuFabricaDDD.Domain.Entities.Robot", b =>
                {
                    b.OwnsOne("TuFabricaDDD.Domain.ValueObjects.Location", "CurrentLocation", b1 =>
                        {
                            b1.Property<Guid>("RobotId")
                                .HasColumnType("uuid");

                            b1.Property<double>("XCoordinate")
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentLocation_X");

                            b1.Property<double>("YCoordinate")
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentLocation_Y");

                            b1.HasKey("RobotId");

                            b1.ToTable("Robots");

                            b1.WithOwner()
                                .HasForeignKey("RobotId");
                        });

                    b.OwnsOne("TuFabricaDDD.Domain.ValueObjects.NetworkLocation", "NetworkLocation", b1 =>
                        {
                            b1.Property<Guid>("RobotId")
                                .HasColumnType("uuid");

                            b1.Property<IPAddress>("IpAddress")
                                .IsRequired()
                                .HasColumnType("inet")
                                .HasColumnName("NetworkLocation_IPAddress");

                            b1.HasKey("RobotId");

                            b1.ToTable("Robots");

                            b1.WithOwner()
                                .HasForeignKey("RobotId");

                            b1.OwnsOne("TuFabricaDDD.Domain.ValueObjects.AccessPoint", "ConnectedAccessPoint", b2 =>
                                {
                                    b2.Property<Guid>("NetworkLocationRobotId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Channel")
                                        .HasColumnType("integer")
                                        .HasColumnName("NetworkLocation_AccessPoint_Bssid");

                                    b2.Property<string>("Ssid")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("NetworkLocation_AccessPoint_Ssid");

                                    b2.HasKey("NetworkLocationRobotId");

                                    b2.ToTable("Robots");

                                    b2.WithOwner()
                                        .HasForeignKey("NetworkLocationRobotId");
                                });

                            b1.Navigation("ConnectedAccessPoint")
                                .IsRequired();
                        });

                    b.Navigation("CurrentLocation")
                        .IsRequired();

                    b.Navigation("NetworkLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
